### ISSUE TITLE
invalid memory address in eksctl_courier_route53_record

### ISSUE THREAD

**Issue by tetsuya28** [mumoshu/terraform-provider-eksctl#12]
I run [`courier_route53_record `](https://github.com/mumoshu/terraform-provider-eksctl#cluster-canary-deployment-using-route-53-and-nlb) tutorial in README.md, and I got following error.

```
2020-09-24T18:45:34.665+0900 [DEBUG] plugin.terraform-provider-eksctl_v0.8.3: 2020/09/24 18:45:34 Setting weight to 10
2020/09/24 18:45:35 [TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
2020-09-24T18:45:35.543+0900 [DEBUG] plugin.terraform-provider-eksctl_v0.8.3: panic: runtime error: invalid memory address or nil pointer dereference
2020-09-24T18:45:35.543+0900 [DEBUG] plugin.terraform-provider-eksctl_v0.8.3: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1accc2c]
2020-09-24T18:45:35.543+0900 [DEBUG] plugin.terraform-provider-eksctl_v0.8.3: 
2020-09-24T18:45:35.543+0900 [DEBUG] plugin.terraform-provider-eksctl_v0.8.3: goroutine 100 [running]:
2020-09-24T18:45:35.543+0900 [DEBUG] plugin.terraform-provider-eksctl_v0.8.3: github.com/k-kinzal/progressived/pkg/provider.(*Route53Provider).Update(0xc000339420, 0x4024000000000000, 0xc000595eb0, 0x1)
2020-09-24T18:45:35.543+0900 [DEBUG] plugin.terraform-provider-eksctl_v0.8.3: 	/Users/***/go/1.14.0/pkg/mod/github.com/k-kinzal/progressived@v0.0.0-20200909013205-9522de740306/pkg/provider/route53.go:105 +0x9c
2020-09-24T18:45:35.543+0900 [DEBUG] plugin.terraform-provider-eksctl_v0.8.3: github.com/mumoshu/terraform-provider-eksctl/pkg/courier.(*Route53RecordSetRouter).TrafficShift(0xc00062c050, 0x2c1c6c0, 0xc0008b6b00, 0x0, 0x0)
2020-09-24T18:45:35.543+0900 [DEBUG] plugin.terraform-provider-eksctl_v0.8.3: 	/Users/***/ghq/github.com/mumoshu/terraform-provider-eksctl/pkg/courier/route53_record_set_router.go:86 +0x5ca
2020-09-24T18:45:35.543+0900 [DEBUG] plugin.terraform-provider-eksctl_v0.8.3: github.com/mumoshu/terraform-provider-eksctl/pkg/provider.createOrUpdateCourierRoute53Record.func1(0x0, 0x0)
2020-09-24T18:45:35.543+0900 [DEBUG] plugin.terraform-provider-eksctl_v0.8.3: 	/Users/***/ghq/github.com/mumoshu/terraform-provider-eksctl/pkg/provider/resource_courier_route53_record_operations.go:91 +0x67
2020-09-24T18:45:35.543+0900 [DEBUG] plugin.terraform-provider-eksctl_v0.8.3: golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0006bed80, 0xc0006bedb0)
2020-09-24T18:45:35.543+0900 [DEBUG] plugin.terraform-provider-eksctl_v0.8.3: 	/Users/***/go/1.14.0/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x59
2020-09-24T18:45:35.543+0900 [DEBUG] plugin.terraform-provider-eksctl_v0.8.3: created by golang.org/x/sync/errgroup.(*Group).Go
2020-09-24T18:45:35.543+0900 [DEBUG] plugin.terraform-provider-eksctl_v0.8.3: 	/Users/***/go/1.14.0/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66
```

I think I solved this by upgrading go module(`k-kinzal/progressived`), so I created the pull request. Please check it:bow:

Sincerely.

**Comment by mumoshu** [comment]
@tetsuya28 Closing this as fixed. Thanks for your help @tetsuya28!
